### ISSUE TITLE
Error on BUY with cbpro

### ISSUE THREAD

**Issue by derricksmith** [ldmonko/wolfinch#26]
Traceback (most recent call last):
  File "Wolfinch.py", line 372, in <module>
    wolfinch_main()
  File "Wolfinch.py", line 116, in wolfinch_main
    process_market(market)
  File "Wolfinch.py", line 137, in process_market
    market.consume_trade_signal(signal, sl, tp)
  File "/opt/wolfinch/market/market.py", line 1245, in consume_trade_signal
    self._execute_market_trade(trade_req_list)
  File "/opt/wolfinch/market/market.py", line 843, in _execute_market_trade
    order = self._buy_order_create (trade_req)
  File "/opt/wolfinch/market/market.py", line 607, in _buy_order_create
    order.stop = trade_req.stop
AttributeError: 'NoneType' object has no attribute 'stop'

**Comment by ldmonko** [comment]
Few questions to get more context -  can you paste the logs before the exception? Are you able to see the order details or the order exec has failed ? did you configure the access tokens correct (with right privileges)? and are you able to see the account access is success during init? Have you tried the simulation mode and does that work ?
